id: A2214BAD4
title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart Practice
  of Vidyādharas, from the Heart Essence of the Vast Expanse
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:02:06.046918
  last_modified_at: 2022-03-01 04:02:06.046925
