id: A2214BAD4
title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:02:06.006848
  last_modified_at: 2022-03-01 04:02:06.006856
